name: Agent

on:
  pull_request:

jobs:
  restyled:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: |
          # Install gh
          cd /tmp
          curl -L -sSf https://github.com/cli/cli/releases/download/v2.53.0/gh_2.53.0_linux_amd64.tar.gz | tar xzvf -
          sudo cp -v gh_*/bin/gh /usr/local/bin
        working-directory: /tmp

      - run: |
          # Add support scripts
          cat > ./set-pr-status <<'EOM'
          #!/usr/bin/env bash
          set -euo pipefail

          args=(
            -f context=restyled
            -f "state=$1"
            -f "description=$2"
            -f "target_url=$3"
          )

          endpoint='repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}'
          exec gh api "$endpoint" "${args[@]}"
          EOM

          chmod +x set-pr-status
          sudo mv -v set-pr-status /usr/local/bin

          sudo apt-get update -y
          sudo apt-get install -y jo

          cat > ./log-info <<'EOM'
          #!/usr/bin/env bash
          while read -r ln; do
            now=$(date --iso-8601=ns --utc | sed 's/,/./; s/+00:00$/Z/;')
            esc=$(sed 's/^@/\\@/' <<<"$ln")
            jo "time=$now" "level=info" "message[text]=${esc:-" "}" "$@"
          done
          EOM

          chmod +x log-info
          sudo mv -v log-info /usr/local/bin

      - run: set-pr-status pending "Restyling" ${{ env.JOB_URL }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: restyled-io/actions/setup@v1
      - id: restyler
        uses: restyled-io/actions/run@v1
        with:
          committer-email: "commits@restyled.io"
          committer-name: "Restyled.io"
          job-url: ${{ env.JOB_URL }}
          log-format: ${{ env.LOG_FORMAT }}
          log-level: ${{ env.LOG_LEVEL }}

      - if: ${{ steps.restyler.outputs.differences == 'true' }}
        run: |
          # Store differences patch
          log-info "context[patch]=true" <<'EOM'
          ${{ steps.restyler.outputs.git-patch }}
          EOM

          log-info <<'EOM'
          NOTE: you can manually apply these fixes by running:

              git checkout <your branch>
              curl ${{ env.JOB_URL }}/patch | git am
              git push

          EOM

      - id: create-pull-request
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          base: ${{ steps.restyler.outputs.restyled-base }}
          branch: ${{ steps.restyler.outputs.restyled-head }}
          title: ${{ steps.restyler.outputs.restyled-title }}
          body: ${{ steps.restyler.outputs.restyled-body }}
          labels: ${{ steps.restyler.outputs.restyled-labels }}
          reviewers: ${{ steps.restyler.outputs.restyled-reviewers }}
          team-reviewers: ${{ steps.restyler.outputs.restyled-team-reviewers }}
          delete-branch: true

      - if: |
          steps.restyler.outputs.differences == 'false' &&
          steps.restyler.outputs.skipped == 'true'
        run: set-pr-status success "Restyling skipped" ${{ env.JOB_URL }}

      - if: |
          steps.restyler.outputs.differences != 'true' &&
          steps.restyler.outputs.skipped != 'true'
        run: set-pr-status success "No differences" ${{ env.JOB_URL }}

      - if: |
          steps.restyler.outputs.differences == 'true' &&
          steps.restyler.outputs.skipped != 'true'
        run: set-pr-status failure "Restyled found differences" '${{ steps.create-pull-request.outputs.pull-request-url }}'

      - if: ${{ failure() }}
        run: set-pr-status error "Restyled errored" ${{ env.JOB_URL }}
