name: CI

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: restyled/restyler
          tags: type=raw,value=gha-rc1
      - uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - uses: extractions/setup-just@v2
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RESTYLED_DEV_APP_ID }}
          private-key: ${{ secrets.RESTYLED_DEV_PRIVATE_KEY }}
      - run: just image-test
        env:
          GITHUB_ACCESS_TOKEN: ${{ steps.app-token.outputs.token }}
